### ISSUE TITLE
Server blocking on CompletableFuture's underlying ThreadPool starvation

### ISSUE THREAD

**Issue by ggeoffrey** [hyperfiddle/hyperfiddle#1038]
In JVM land, promesa's promises are backed by CompletableFuture, which implicitly relies on a fixed-size thread pool.

Something in our code, we don't know where, is presumably causing a promise to never resolve nor reject, without any timeout. This code path is executed intensively during a fiddle render and the CompletableFuture thread pool fills up quickly, making the app unusable.

@dustingetz supposes it might be caused by a try/catch block catching the error, discarding it (noop) and not rejecting the promise. A break-on-exception debugger might be able to locate which code form is causing it.

Here is a stack trace of the incriminated thread:

```
qtp2078089808-43" #43 prio=5 os_prio=31 tid=0x00007f9ec3549000 nid=0x13603 waiting on condition [0x000070000f85f000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000074a8a34c8> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
        at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:438)
        at contrib.do$from_async.invokeStatic(do.cljc:56)
        at contrib.do$from_async.invoke(do.cljc:55)
        at hyperfiddle.service.dispatch$render$fn__31540$fn__31541.invoke(dispatch.clj:140)
        at hyperfiddle.service.dispatch$render$fn__31540.invoke(dispatch.clj:134)
        at hyperfiddle.service.dispatch$render.invokeStatic(dispatch.clj:132)
        at hyperfiddle.service.dispatch$render.invoke(dispatch.clj:131)
        at hyperfiddle.app.HF-App.render(app.clj:156)
        at hyperfiddle.service.resolve$eval17628$fn__17771$G__17612__17774.invoke(resolve.cljc:79)
        at hyperfiddle.service.resolve$eval17628$fn__17771$G__17611__17778.invoke(resolve.cljc:79)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
```

If our assumptions are correct, I would advise to:
- don't `catch` and discard (at least log an ERROR),
- force a high default timeout on all promises, like 5min[¹], so we get a stack trace and can find which promise is causing the issue.
- provide a DEBUG level audit tool (alter `defn` vars to wrap invocations, log and time function calls)

[¹] This is an arbitrary number, but in Hyperfiddle no operation should block for so long. Except me, who blocked way more than 5min on this issue. If I had such timeout I'd have saw the timeout stack trace while debugging.

**Comment by dustingetz** [comment]
IMO this looks like a simple crash. Crashing code is not the type of thing that needs to be caught and/or propagated via promise rejection. We have to write code that doesn't crash.

**Comment by dustingetz** [comment]
Timeouts aren't great because when we hit breakpoints in the debugger, we don't want the timeouts to trigger

**Comment by ggeoffrey** [comment]
`We have to write code that doesn't crash.` I can only agree with this. But when it unfortunately happens, I'd like to know where.

**Comment by dustingetz** [comment]
The issue is written up in such a way as to suggest there is a missing catch handler somewhere in hyperfiddle server code. That doesn't seem to be the problem. It's not the server's job to catch e.g. SyntaxError and propagate it back as a rejected promise. Maybe the underlying async implementation be configured to log uncaught exceptions in an async frame?

**Comment by dustingetz** [comment]
Or, maybe that is already happening and the bug IS that the server is catching a syntax error *that it shouldn't* and throwing it away, when it should have been allowed to crash the thread so the async impl could report it to console.

**Comment by ggeoffrey** [comment]
You are right, these are important clarifications.

**Comment by ggeoffrey** [comment]
I edited this:
```diff
(defn as-p [v]
   (p/then v identity))
  
 (defmacro do-async [& body]
-  `(as-p (p/resolved (try ~@body
-                          (catch ~(if (:ns &env) 'js/Error 'Exception) e# (p/rejected e#))))))
+  `(try (p/resolved ~@body)
+        (catch ~(if (:ns &env) 'js/Error 'Exception) e# (prn e#) (p/rejected e#))))
```
And it gave me this message: `Stack trace of root exception is empty; this is likely due to a JVM optimization that can be disabled with -XX:-OmitStackTraceInFastThrow.`

After I added the JVM flag, I've got this stack trace:

```
                                               java.lang.Thread.run              Thread.java:  748
               org.eclipse.jetty.util.thread.QueuedThreadPool$2.run    QueuedThreadPool.java:  678
              org.eclipse.jetty.util.thread.QueuedThreadPool.runJob    QueuedThreadPool.java:  760
                         org.eclipse.jetty.io.ChannelEndPoint$2.run     ChannelEndPoint.java:  118
                         org.eclipse.jetty.io.FillInterest.fillable        FillInterest.java:  102
     org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded  AbstractConnection.java:  281
                 org.eclipse.jetty.server.HttpConnection.onFillable      HttpConnection.java:  260
                        org.eclipse.jetty.server.HttpChannel.handle         HttpChannel.java:  352
                             org.eclipse.jetty.server.Server.handle              Server.java:  531
             org.eclipse.jetty.server.handler.HandlerWrapper.handle      HandlerWrapper.java:  132
              org.eclipse.jetty.server.handler.ScopedHandler.handle       ScopedHandler.java:  144
            org.eclipse.jetty.server.handler.ContextHandler.doScope      ContextHandler.java: 1155
           org.eclipse.jetty.server.handler.ScopedHandler.nextScope       ScopedHandler.java:  201
                   org.eclipse.jetty.servlet.ServletHandler.doScope      ServletHandler.java:  473
           org.eclipse.jetty.server.handler.ScopedHandler.nextScope       ScopedHandler.java:  203
           org.eclipse.jetty.server.handler.ContextHandler.doHandle      ContextHandler.java: 1253
          org.eclipse.jetty.server.handler.ScopedHandler.nextHandle       ScopedHandler.java:  257
             org.eclipse.jetty.server.handler.HandlerWrapper.handle      HandlerWrapper.java:  132
           org.eclipse.jetty.server.handler.gzip.GzipHandler.handle         GzipHandler.java:  724
              org.eclipse.jetty.server.handler.ScopedHandler.handle       ScopedHandler.java:  146
                  org.eclipse.jetty.servlet.ServletHandler.doHandle      ServletHandler.java:  535
                     org.eclipse.jetty.servlet.ServletHolder.handle       ServletHolder.java:  865
                         io.pedestal.http.servlet.FnServlet/service              servlet.clj:   28
io.pedestal.http.impl.servlet-interceptor/interceptor-service-fn/fn  servlet_interceptor.clj:  351
                              io.pedestal.interceptor.chain/execute                chain.clj:  389
                              io.pedestal.interceptor.chain/execute                chain.clj:  379
                            io.pedestal.interceptor.chain/enter-all                chain.clj:  235
                          io.pedestal.interceptor.chain/process-all                chain.clj:  186
                                                                ...                               
                                        clojure.core/with-bindings*                 core.clj: 1973 (repeats 2 times)
                                                 clojure.core/apply                 core.clj:  665
                                                                ...                               
                       io.pedestal.interceptor.chain/process-all/fn                chain.clj:  188
             io.pedestal.interceptor.chain/process-all-with-binding                chain.clj:  171
                                io.pedestal.interceptor.chain/try-f                chain.clj:   54
                                                                ...                               
                                           contrib.do/with-scope/fn                  do.cljc:   78
                                                 clojure.core/apply                 core.clj:  665
                                                                ...                               
                   hyperfiddle.ide.service.pedestal/eval31600/fn/fn             pedestal.clj:   75
                                                                ...                               
                          hyperfiddle.service.dispatch/eval31538/fn             dispatch.clj:  129
                                                                ...                               
                                    hyperfiddle.service.resolve/via             resolve.cljc:  103
                                    hyperfiddle.service.resolve/via             resolve.cljc:  104
                                                 clojure.core/apply                 core.clj:  669
                                                                ...                               
                         hyperfiddle.service.resolve/eval17628/fn/G             resolve.cljc:   79 (repeats 2 times)
                                      hyperfiddle.app.HF-App/render                  app.clj:  156
                                hyperfiddle.service.dispatch/render             dispatch.clj:  132
                             hyperfiddle.service.dispatch/render/fn             dispatch.clj:  134
                          hyperfiddle.service.dispatch/render/fn/fn             dispatch.clj:  143
                                                 clojure.core/apply                 core.clj:  665
java.lang.NullPointerException: 
```

Since fixing this stack trace cause is not related to this issue, I consider this issue can be closed.

**Comment by dustingetz** [comment]
I don't understand the difference in do-async, what's going on, very nice find btw

**Comment by dustingetz** [comment]
Oh I see you added a `prn`, are the other changes significant?

**Comment by dustingetz** [comment]
`p/then` (in `as-p`) is possibly performing a flatten, whose behavior is relevant here, because body can evaluate to a promise

I would expect not to want to randomly log rejected promises, the person who ultimately inspects the promise up-stack should be deciding to log (likely someone up-stack is just dropping an error on the floor, which should be fixed at that point)

**Comment by ggeoffrey** [comment]
The `prn` is of course for debug purposes, I didn't commit it.
You are right about the `p/then v identity`, it's probably flattening, which would explain the nested `(p/resolved (p/rejected err))`
There's still some work to do since this is actually a rabbit hole and I haven't reached the bottom yet.
