### ISSUE TITLE
Unhandled rejection Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#199]
Express is imperative, order of response setters matters very much

**Comment by dustingetz** [comment]
```
dmbp17:target dustin$ ./run.sh 
Debugger listening on ws://127.0.0.1:9229/49cfdba6-c4c4-4389-b43e-6dfd64cc6cf4
For help see https://nodejs.org/en/docs/inspector
2018-04-17T17:49:11.821Z INFO [main.main:32] - Root server started on port: 3000
2018-04-17T17:49:22.694Z DEBUG [main.server:42] - router: :edge "/"
2018-04-17T17:49:22.701Z DEBUG [hyperfiddle.io.http.core:15] - Issuing request [-1297054454] http://www-admin.hyperfiddle.site/api/dev/global-basis
2018-04-17T17:49:25.785Z DEBUG [hyperfiddle.io.http.core:46] - Request succeeded [-1297054454] total time: 3085.3ms
2018-04-17T17:49:25.789Z DEBUG [hyperfiddle.io.hydrate-requests:46] - hydrate-requests! request count= 1 basis= {#uri "datomic:free://datomic:4334/domains" 1519} form= {:staged-branches (), :request [#hypercrud.types.EntityRequest.EntityRequest{:e [:domain/ident "www...
2018-04-17T17:49:25.790Z DEBUG [hyperfiddle.io.http.core:15] - Issuing request [1528350856] http://www-admin.hyperfiddle.site/api/dev/hydrate-requests/eyN1cmkgImRhdG9taWM6ZnJlZTovL2RhdG9taWM6NDMzNC9kb21haW5zIiAxNTE5fQ,,
2018-04-17T17:49:25.857Z DEBUG [hyperfiddle.io.http.core:46] - Request succeeded [1528350856] total time: 67.3ms
2018-04-17T17:49:25.862Z DEBUG [hyperfiddle.ide:179] - ([#uri "datomic:free://datomic:4334/domains" 1519] [#uri "datomic:free://datomic:4334/hyperfiddle-blog" 2216] [#uri "datomic:free://datomic:4334/hyperfiddle-blog-source" 1153] [#uri "datomic:free://datomic:4334/root" 16925])
2018-04-17T17:49:25.866Z DEBUG [hyperfiddle.io.http.core:15] - Issuing request [259336760] http://www-admin.hyperfiddle.site/api/dev/hydrate-route/KFsjdXJpICJkYXRvbWljOmZyZWU6Ly9kYXRvbWljOjQzMzQvZG9tYWlucyIgMTUxOV0gWyN1cmkgImRhdG9taWM6ZnJlZTovL2RhdG9taWM6NDMzNC9kb21haW5zIiAxNTE5XSBbI3VyaSAiZGF0b21pYzpmcmVlOi8vZGF0b21pYzo0MzM0L2h5cGVyZmlkZGxlLWJsb2ciIDIyMTZdIFsjdXJpICJkYXRvbWljOmZyZWU6Ly9kYXRvbWljOjQzMzQvaHlwZXJmaWRkbGUtYmxvZy1zb3VyY2UiIDExNTNdIFsjdXJpICJkYXRvbWljOmZyZWU6Ly9kYXRvbWljOjQzMzQvcm9vdCIgMTY5MjVdKQ,,/WzpoeXBlcmZpZGRsZS5ibG9nL3Bvc3QgWyNlbnRpdHlbIiQiIDpoeXBlcmZpZGRsZS5ibG9nL2hvbWVwYWdlXV1d/bmls/ezpoeXBlcmZpZGRsZS5pZGUvZm9vICJwYWdlIn0,
2018-04-17T17:49:26.709Z DEBUG [hyperfiddle.io.http.core:46] - Request succeeded [259336760] total time: 843.4ms
2018-04-17T17:49:26.738Z ERROR [hyperfiddle.service.node.ssr:167] - 
TypeError: reagent.dom.server.module(...).renderToNodeStream is not a function
Unhandled rejection Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at validateHeader (_http_outgoing.js:503:11)
    at ServerResponse.setHeader (_http_outgoing.js:510:3)
    at vary (/Users/dustin/src/hfnet/cloud-node/target/node_modules/vary/index.js:147:9)
    at ServerResponse.res.vary (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/response.js:967:3)
    at ServerResponse.res.format (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/response.js:667:8)
    at /Users/dustin/src/hfnet/cloud-node/target/main.out/hyperfiddle/service/node/ssr.cljs:168:20
    at /Users/dustin/src/hfnet/cloud-node/target/main.out/promesa/impl.cljc:59:22
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at Promise.promesa.impl.Promise.promesa$protocols$IPromise$_catch$arity$2 (/Users/dustin/src/hfnet/cloud-node/target/main.out/promesa/impl.cljc:59:17)
    at Object.promesa$protocols$_catch [as _catch] (/Users/dustin/src/hfnet/cloud-node/target/main.out/promesa/protocols.cljc:32:12)
    at Function.promesa.core.catch$.cljs$core$IFn$_invoke$arity$2 (/Users/dustin/src/hfnet/cloud-node/target/main.out/promesa/core.cljc:158:5)
    at hyperfiddle$service$node$ssr$http_edge (/Users/dustin/src/hfnet/cloud-node/target/main.out/hyperfiddle/service/node/ssr.cljs:166:10)
    at Function.G__10589__2 [as cljs$core$IFn$_invoke$arity$2] (/Users/dustin/src/hfnet/cloud-node/target/main.out/cljs/core.cljs:4254:14)
    at Object.cljs$core$apply_to [as apply_to] (/Users/dustin/src/hfnet/cloud-node/target/main.out/cljs/core.cljs:3831:1)
    at Function.cljs.core.apply.cljs$core$IFn$_invoke$arity$4 (/Users/dustin/src/hfnet/cloud-node/target/main.out/cljs/core.cljs:3894:11)
    at main.server.build_express_router (/Users/dustin/src/hfnet/cloud-node/target/main.out/main/server.cljs:43:10)
    at Layer.handle [as handle_request] (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/layer.js:95:5)
    at /Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/index.js:281:22
    at param (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/index.js:275:10)
    at /Users/dustin/src/hfnet/cloud-node/target/node_modules/express-winston/index.js:291:9
    at Layer.handle [as handle_request] (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/index.js:317:13)
    at /Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/dustin/src/hfnet/cloud-node/target/node_modules/express/lib/router/index.js:275:10)
    at textParser (/Users/dustin/src/hfnet/cloud-node/target/node_modules/body-parser/lib/types/text.js:69:7)
```

**Comment by dustingetz** [comment]
This was due to not running yarn :(
